const PRODUCT = {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
  CLEAR_DATA: "CLEAR_DATA",
  SET_STATE_REDUCER: "SET_STATE_REDUCER"
};

const USER = {
  SIGNUP: "USER_SIGNUP",
  SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  SIGNUP_FAIL: "USER_SIGNUP_FAIL",
  SIGNIN: "USER_SIGNIN",
  SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  SIGNIN_FAIL: "USER_SIGNIN_FAIL",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  UPDATE_STATE: "UPDATE_STATE"
  // LOGOUT: "USER_LOGOUT",
  // LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  // LOGOUT_FAIL: "USER_LOGOUT_FAIL",
  // GET_MY_INFO: "GET_MY_INFO",
  // GET_MY_INFO_SUCCESS: "GET_MY_INFO_SUCCESS",
  // GET_MY_INFO_FAIL: "GET_MY_INFO_FAIL"
};

const LIST_USER = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  GET_LIST_USER_FAIL: "GET_LIST_USER_FAIL",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FAIL: "GET_USER_BY_ID_FAIL",
  EDIT_USER: "EDIT_USER",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",
  SET_STATE_REDUCER: "SET_STATE_REDUCER"
};

const ADVERTISING = {
  GET_LIST_ADS: "GET_LIST_ADS",
  GET_LIST_ADS_SUCCESS: "GET_LIST_ADS_SUCCESS",
  GET_LIST_ADS_FAIL: "GET_LIST_ADS_FAIL",
  GET_ADS_BY_ID: "GET_ADS_BY_ID",
  GET_ADS_BY_ID_SUCCESS: "GET_ADS_BY_ID_SUCCESS",
  GET_ADS_BY_ID_FAIL: "GET_ADS_BY_ID_FAIL",
  EDIT_ADS: "EDIT_ADS",
  EDIT_ADS_SUCCESS: "EDIT_ADS_SUCCESS",
  EDIT_ADS_FAIL: "EDIT_ADS_FAIL",
  SET_STATE_REDUCER: "SET_STATE_REDUCER"
};

export { PRODUCT, USER, LIST_USER, ADVERTISING };
