const PRODUCT = {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
  CLEAR_DATA: "CLEAR_DATA",
  SET_STATE_REDUCER: "SET_STATE_REDUCER",
};

const USER = {
  SIGNUP: "USER_SIGNUP",
  SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  SIGNUP_FAIL: "USER_SIGNUP_FAIL",
  SIGNIN: "USER_SIGNIN",
  SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  SIGNIN_FAIL: "USER_SIGNIN_FAIL",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  UPDATE_STATE: "UPDATE_STATE",
};

const LIST_USER = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  GET_LIST_USER_FAIL: "GET_LIST_USER_FAIL",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FAIL: "GET_USER_BY_ID_FAIL",
  EDIT_USER: "EDIT_USER",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",
  SET_STATE_REDUCER: "SET_STATE_REDUCER",
  SEARCH_USER: "SEARCH_USER",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAIL: "SEARCH_USER_FAIL",
};

const ADVERTISING = {
  GET_LIST_ADS: "GET_LIST_ADS",
  GET_LIST_ADS_SUCCESS: "GET_LIST_ADS_SUCCESS",
  GET_LIST_ADS_FAIL: "GET_LIST_ADS_FAIL",
  GET_ADS_BY_ID: "GET_ADS_BY_ID",
  GET_ADS_BY_ID_SUCCESS: "GET_ADS_BY_ID_SUCCESS",
  GET_ADS_BY_ID_FAIL: "GET_ADS_BY_ID_FAIL",
  EDIT_ADS: "EDIT_ADS",
  EDIT_ADS_SUCCESS: "EDIT_ADS_SUCCESS",
  EDIT_ADS_FAIL: "EDIT_ADS_FAIL",
  SET_STATE_REDUCER: "SET_STATE_REDUCER",
  DELETE_ADS: "DELETE_ADS",
  DELETE_ADS_SUCCESS: "DELETE_ADS_SUCCESS",
  DELETE_ADS_FAIL: "DELETE_ADS_FAIL",
  ADD_NEW_ADS: "ADD_NEW_ADS",
  ADD_NEW_ADS_SUCCESS: "ADD_NEW_ADS_SUCCESS",
  ADD_NEW_ADS_FAIL: "ADD_NEW_ADS_FAIL",
  SEARCH_ADS: "SEARCH_ADS",
  SEARCH_ADS_SUCCESS: "SEARCH_ADS_SUCCESS",
  SEARCH_ADS_FAIL: "SEARCH_ADS_FAIL",
};

const SOCIAL_MEDIA = {
  GET_LIST_SOCIAL_MEDIA: "GET_LIST_SOCIAL_MEDIA",
  GET_LIST_SOCIAL_MEDIA_SUCCESS: "GET_LIST_SOCIAL_MEDIA_SUCCESS",
  GET_LIST_SOCIAL_MEDIA_FAIL: "GET_LIST_SOCIAL_MEDIA_FAIL",
  GET_BY_ID: "GET_BY_ID",
  GET_BY_ID_SUCCESS: "GET_BY_ID_SUCCESS",
  GET_BY_ID_FAIL: "GET_BY_ID_FAIL",
  EDIT_SOCIAL_MEDIA: "EDIT_SOCIAL_MEDIA",
  EDIT_SOCIAL_MEDIA_SUCCESS: "EDIT_SOCIAL_MEDIA_SUCCESS",
  EDIT_SOCIAL_MEDIA_FAIL: "EDIT_SOCIAL_MEDIA_FAIL",
  ADD_NEW: "ADD_NEW",
  ADD_NEW_SUCCESS: "ADD_NEW_SUCCESS",
  ADD_NEW_FAIL: "ADD_NEW_FAIL",
  DELETE_SOCIAL_MEDIA: "DELETE_SOCIAL_MEDIA",
  DELETE_SOCIAL_MEDIA_SUCCESS: "DELETE_SOCIAL_MEDIA_SUCCESS",
  DELETE_SOCIAL_MEDIA_FAIL: "DELETE_SOCIAL_MEDIA_FAIL",
  SEARCH_SOCIAL_MEDIA: "SEARCH_SOCIAL_MEDIA",
  SEARCH_SOCIAL_MEDIA_SUCCESS: "SEARCH_SOCIAL_MEDIA_SUCCESS",
  SEARCH_SOCIAL_MEDIA_FAIL: "SEARCH_SOCIAL_MEDIA_FAIL",
  SET_STATE_REDUCER: "SET_STATE_REDUCER",
  GET_LIST_USER: "GET_LIST_USER",
};

const EXCHANGE = {
  CREATE_EXCHANGE: "CREATE_EXCHANGE",
  CREATE_EXCHANGE_SUCCESS: "CREATE_EXCHANGE_SUCCESS",
  CREATE_EXCHANGE_FAIL: "CREATE_EXCHANGE_FAIL",
  UPDATE_EXCHANGE_REDUCER: " UPDATE_EXCHANGE_REDUCER",
  GET_HISTORY_EXCHANGE: "GET_HISTORY_EXCHANGE",
  GET_HISTORY_EXCHANGE_SUCCESS: "GET_HISTORY_EXCHANGE_SUCCESS",
  GET_HISTORY_EXCHANGE_FAIL: "GET_HISTORY_EXCHANGE_FAIL",
};

const UPLOAD = {
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_CONTRACT_SUCCESS: "UPLOAD_IMAGE_CONTRACT_SUCCESS",
  UPLOAD_IMAGE_FAIL: "UPLOAD_IMAGE_FAIL",
  UPDATE_STATE_UPLOAD_REDUCER: "UPDATE_STATE_UPLOAD_REDUCER",
};

export {
  PRODUCT,
  USER,
  LIST_USER,
  ADVERTISING,
  SOCIAL_MEDIA,
  EXCHANGE,
  UPLOAD,
};
